- name: Setup CKS Master Node
  hosts: masters
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_master.sh
        dest: /tmp/install_master.sh
        mode: '0755'

    - name: Run master install script
      ansible.builtin.shell: bash /tmp/install_master.sh
      register: install_output
      ignore_errors: yes

    # - name: Install master setup script
    #   ansible.builtin.shell: |
    #     curl -s k8/install_master.sh | bash
    #   register: install_output
    #   ignore_errors: yes
      
    - name: Show install script output
      debug:
        var: install_output.stdout_lines

    - name: Show install script error
      debug:
        var: install_output.stderr_lines  
    - name: Print exit code
      debug:
        var: install_output.rc    
# - name: Setup CKS Master Node
#   hosts: masters
#   become: yes
#   tasks:
#     - name: Install master setup script
#       ansible.builtin.shell: |        
#         sudo bash -c "bash <(curl -s k8/install_master.sh)"
#       args:
#         executable: /bin/bash 
    # - name: Install master setup script      
    #   shell: |
    #     bash <(curl -s k8/install_master.sh)
    #     # bash <(curl -s https://raw.githubusercontent.com/killer-sh/cks-course-environment/master/cluster-setup/latest/install_master.sh)
