- name: Setup CKS Master Node
  hosts: masters
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_master.sh
        dest: /tmp/install_master.sh
        mode: '0755'

    - name: Run master install script
      ansible.builtin.shell: bash /tmp/install_master.sh
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      register: install_output
      ignore_errors: yes

    - name: Ensure SSH directory exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Print private key length (debug)
      debug:
        msg: "Length of private_key_pem: {{ private_key_pem | length }}" 

    - name: Copy private SSH key to master node for intra-node SSH
      copy:
        # content: "{{ lookup('env', 'PRIVATE_KEY_PEM') }}"
        content: "{{ private_key_pem }}"
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Ensure root SSH directory exists
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0700' 

    # - name: Add public key to root authorized_keys
    #   authorized_key:
    #     user: root
    #     key: "{{ public_key_openssh }}" 

    - name: Copy private key to root
      copy:
        content: "{{ private_key_pem }}"
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: '0600'

    - name: Add target hosts to known_hosts
      known_hosts:
        path: /home/ubuntu/.ssh/known_hosts
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
      loop:
        - cks-worker
        - cks-master
    
    - name: Get kubeadm join command from master
      ansible.builtin.command: kubeadm token create --print-join-command --ttl 0
      register: join_cmd
      when: install_output.rc == 0
      changed_when: false

    - name: Save kubeadm join command to file
      copy:
        content: "{{ join_cmd.stdout }}"
        dest: "/tmp/kubeadm_join_cmd.sh"
      delegate_to: localhost
      run_once: true  
