- name: Setup CKS Master Node
  hosts: masters
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_master.sh
        dest: /tmp/install_master.sh
        mode: '0755'

    - name: Run master install script
      ansible.builtin.shell: bash /tmp/install_master.sh
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      register: install_output
      ignore_errors: yes

    - name: Get kubeadm join command from master
      ansible.builtin.command: kubeadm token create --print-join-command --ttl 0
      register: join_cmd
      when: install_output.rc == 0
      changed_when: false

    - name: Save join command to file (on localhost)
      local_action:
        module: copy
        content: "{{ join_cmd.stdout }}"
        dest: /tmp/kubeadm_join_cmd.sh
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Set join command fact
      set_fact:
        kube_join_cmd: "{{ join_cmd.stdout }}"

    