- name: Setup CKS Master Node
  hosts: master
  become: yes
  tasks:
    - name: Install master setup script
      shell: |
        bash <(curl -s https://raw.githubusercontent.com/killer-sh/cks-course-environment/master/cluster-setup/latest/install_master.sh)
