- name: Setup CKS Master Node
  hosts: masters
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_master.sh
        dest: /tmp/install_master.sh
        mode: '0755'

    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/calico.yaml
        dest: /tmp/calico.yaml
        mode: '0755'    

    - name: Run master install script
      ansible.builtin.shell: bash /tmp/install_master.sh
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      # register: install_output
    #   register: master_install_result
    #   ignore_errors: true

    # - name: Show script stdout
    #   debug:
    #     var: master_install_result.stdout_lines

    # - name: Show script stderr
    #   debug:
    #     var: master_install_result.stderr_lines  

    # - name: Fail if master install fails
    #   ansible.builtin.fail:
    #     msg: "install_master.sh failed with rc {{ master_install_result.rc }}"
    #   when: master_install_result.rc != 0

    # - name: Wait for kubeadm to be available
    #   ansible.builtin.command: which kubeadm
    #   register: kubeadm_check
    #   retries: 5
    #   delay: 10
    #   until: kubeadm_check.rc == 0
    #   become: yes

    # - name: Get kubeadm join command
    #   ansible.builtin.shell: kubeadm token create --print-join-command
    #   register: join_command
    #   become: yes

    # # - name: Get kubeadm join command
    # #   ansible.builtin.shell: kubeadm token create --print-join-command
    # #   register: join_command
    # #   become: yes  
    
    # - name: Set fact with join command
    #   ansible.builtin.set_fact:
    #     kube_join_cmd: "{{ join_command.stdout }}"






    # - name: Install master setup script
    #   ansible.builtin.shell: |
    #     curl -s k8/install_master.sh | bash
    #   register: install_output
    #   ignore_errors: yes
      
    - name: Show install script output
      debug:
        var: install_output.stdout_lines

    - name: Show install script error
      debug:
        var: install_output.stderr_lines  
    - name: Print exit code
      debug:
        var: install_output.rc    
# - name: Setup CKS Master Node
#   hosts: masters
#   become: yes
#   tasks:
#     - name: Install master setup script
#       ansible.builtin.shell: |        
#         sudo bash -c "bash <(curl -s k8/install_master.sh)"
#       args:
#         executable: /bin/bash 
    # - name: Install master setup script      
    #   shell: |
    #     bash <(curl -s k8/install_master.sh)
    #     # bash <(curl -s https://raw.githubusercontent.com/killer-sh/cks-course-environment/master/cluster-setup/latest/install_master.sh)
