- name: Setup CKS Master Node
  hosts: masters
  become: yes
  tasks:
    - name: Install master setup script
      ansible.builtin.shell: |
        curl -s k8/install_master.sh | bash
  register: install_output
  ignore_errors: yes
  
- name: Show install script output
  debug:
    var: install_output.stdout_lines

- name: Show install script error
  debug:
    var: install_output.stderr_lines  
# - name: Setup CKS Master Node
#   hosts: masters
#   become: yes
#   tasks:
#     - name: Install master setup script
#       ansible.builtin.shell: |        
#         sudo bash -c "bash <(curl -s k8/install_master.sh)"
#       args:
#         executable: /bin/bash 
    # - name: Install master setup script      
    #   shell: |
    #     bash <(curl -s k8/install_master.sh)
    #     # bash <(curl -s https://raw.githubusercontent.com/killer-sh/cks-course-environment/master/cluster-setup/latest/install_master.sh)
