- name: Setup CKS Worker Node
  hosts: workers
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_worker.sh
        dest: /tmp/install_worker.sh
        mode: '0755'

    - name: Run worker install script
      ansible.builtin.shell: bash /tmp/install_worker.sh
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      register: worker_script_output

    - name: Ensure SSH directory exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Print private key length (debug)
      debug:
        msg: "Length of private_key_pem_wk: {{ private_key_pem_wk | length }}" 

    - name: Copy private SSH key to master node for intra-node SSH
      copy:
        # content: "{{ lookup('env', 'PRIVATE_KEY_PEM') }}"
        content: "{{ private_key_pem_wk }}"
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'  

    - name: Ensure root SSH directory exists
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy private key to root
      copy:
        content: "{{ private_key_pem }}"
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: '0600'

    # - name: Add target hosts to known_hosts
    #   known_hosts:
    #     path: /home/ubuntu/.ssh/known_hosts
    #     name: "{{ item }}"
    #     key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
    #   loop:
    #     - cks-worker
    #     - cks-master    

    # - name: Add public key to root authorized_keys
    #   authorized_key:
    #     user: root
    #     key: "{{ public_key_openssh }}"    
    
    - name: Read join command from file
      set_fact:
        kube_join_cmd: "{{ lookup('file', '/tmp/kubeadm_join_cmd.sh') }}"
      delegate_to: localhost
      run_once: true

    - name: Join worker to cluster
      ansible.builtin.shell: "{{ kube_join_cmd }}"

    