- name: Setup CKS Worker Node
  hosts: workers
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_worker.sh
        dest: /tmp/install_worker.sh
        mode: '0755'

    - name: Run worker install script
      ansible.builtin.shell: bash /tmp/install_worker.sh
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      register: worker_script_output
    
    - name: Read join command from file
      set_fact:
        kube_join_cmd: "{{ lookup('file', '/tmp/kubeadm_join_cmd.sh') }}"
      delegate_to: localhost
      run_once: true

    - name: Join worker to cluster
      ansible.builtin.shell: "{{ kube_join_cmd }}"

    