- name: Setup CKS Worker Node
  hosts: workers
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_worker.sh
        dest: /tmp/install_worker.sh
        mode: '0755'

    - name: Run master install script
      ansible.builtin.shell: bash /tmp/install_worker.sh
      register: install_output
      ignore_errors: yes

    # - name: Wait for master to write join command file
    #   wait_for:
    #     path: /tmp/kubeadm_join.sh
    #     timeout: 120
    #   delegate_to: master

    # - name: Fetch join command from master
    #   fetch:
    #     src: /tmp/kubeadm_join.sh
    #     dest: /tmp/kubeadm_join.sh
    #     flat: yes
    #   delegate_to: master

    # - name: Copy join command to worker
    #   copy:
    #     src: /tmp/kubeadm_join.sh
    #     dest: /tmp/kubeadm_join.sh
    #     mode: '0755'

    # - name: Join Kubernetes Cluster
    #   shell: bash /tmp/kubeadm_join.sh  
    
    