- name: Setup CKS Worker Node
  hosts: workers
  become: yes
  tasks:
    - name: Copy master install script to remote
      ansible.builtin.copy:
        src: k8/install_worker.sh
        dest: /tmp/install_worker.sh
        mode: '0755'

    # - name: Run master install script
    #   # ansible.builtin.shell: |
    #   #   bash <(curl -s https://raw.githubusercontent.com/shavamhofu/cks-cluster-gcp/main/ansible/k8/install_worker.sh)
    #   # args:
    #   #   executable: /bin/bash
    #   ansible.builtin.shell: bash /tmp/install_worker.sh
    #   # ansible.builtin.script: bash ansible/k8/install_worker.sh
    #   register: worker_script_output
      # ignore_errors: yes
    - name: Run master install script
      ansible.builtin.shell: bash /tmp/install_worker.sh
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      register: install_output

    - name: Debug worker script output
      debug:
        var: worker_script_output.stdout_lines  

    - name: Copy kubeadm join script from control to worker
      ansible.builtin.copy:
        src: /tmp/kubeadm_join.sh
        dest: /tmp/kubeadm_join.sh
        mode: '0755'

    - name: Join worker to Kubernetes cluster
      ansible.builtin.shell: bash /tmp/kubeadm_join.sh
      when: worker_script_output.rc == 0


    # - name: Wait for master to write join command file
    #   wait_for:
    #     path: /tmp/kubeadm_join.sh
    #     timeout: 120
    #   delegate_to: masters

    # - name: Fetch join command from master
    #   fetch:
    #     src: /tmp/kubeadm_join.sh
    #     dest: /tmp/kubeadm_join.sh
    #     flat: yes
    #   delegate_to: masters

    # - name: Copy join command to worker
    #   copy:
    #     src: /tmp/kubeadm_join.sh
    #     dest: /tmp/kubeadm_join.sh
    #     mode: '0755'

    # - name: Join Kubernetes Cluster
    #   shell: bash /tmp/kubeadm_join.sh  
    
    