- name: Setup CKS Worker Node
  hosts: worker
  become: yes
  tasks:
    - name: Install worker setup script
      shell: |
        bash <(curl -s k8/install_worker.sh)
        # bash <(curl -s https://raw.githubusercontent.com/killer-sh/cks-course-environment/master/cluster-setup/latest/install_worker.sh)
